### ISSUE TITLE
PyJWT released a new preview version, which breaks Oauth in FAB

### ISSUE THREAD

**Issue by yhvicey** [dpgaspar/Flask-AppBuilder#1511]
### Environment

Flask-Appbuilder version: latest

PyJWT released a [new version](https://pypi.org/project/PyJWT/2.0.0a1/), which breaks Oauth [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L671). Looks like now `jwt.encode` returns `str` directly and it will cause below error:

```
ERROR:flask_appbuilder.security.views:Error on OAuth authorize: 'str' object has no attribute 'decode'
```

**Comment by dpgaspar** [comment]
@yhvicey, Thank you for reporting it. It seems it's not officially released yet, and PyJWT is a Flask-jwt-extended (and that dependency has no upper limits there). 

Still not invested much time, but it seems strange that pyJWT breaks OAuth since it does not seem like a dependency from authlib. Can you share the crash log? does it work with pyjwt 1.7.1?

**Comment by yhvicey** [comment]
We forked FAB into a private repo and will run `python setup.py install` each time we do a release, so it just downloaded that pre-release version and used it (not sure why pip would use pre-release version by default without configuration). I'll try give repro steps later.

**Comment by yhvicey** [comment]
Repro steps:
1. Clone FAB repo
1. Create a virtual environment and activate it
1. Run `python setup.py install`
1. Run `pip freeze --local | grep PyJWT`
1. You'll see `PyJWT==2.0.0a1`

**Comment by lepture** [comment]
Authlib has its own JWT implementation in `authlib.jose`. It doesn't use pyJWT.

**Comment by yhvicey** [comment]
I've attached link to broken line, it's not about `authlib` but FAB itself, see [this line at flask_appbuilder/security/views.py](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L671)

**Comment by dpgaspar** [comment]
Ok @yhvicey check if https://github.com/dpgaspar/Flask-AppBuilder/pull/1522 fixes the issue

**Comment by yhvicey** [comment]
> Ok @yhvicey check if #1522 fixes the issue

IMHO to minimize the change we should pin `PyJWT` to `1.7.1`, I'm not sure if there're still places to fix, but I'll be happy to help test if this mitigated the issue as well

**Comment by dpgaspar** [comment]
Yes right you are, just grabbed a cup of coffee ;)

Updated!

**Comment by yhvicey** [comment]
LGTM, really appreciate your help!
